### ISSUE TITLE
[Platform Client] HDX-button in data-export-settings

### ISSUE THREAD

**Issue by Angamanga** [ushahidi/platform-client#1119]
### Behaviour:
- In the data-export-settings
1. If the HDX-feature-flag is turned on...  
 a. A button for HDX-exports should be added according to designs
https://xd.adobe.com/view/2690f082-d88d-4788-5db7-b04c9474a404-50a1/screen/9528cb6c-dcb2-43ef-aa90-0dd0842cff6a/Data-export-CSV-landing-page-HDX
 
 b. If no api-key is added by the user, a text and link to the api-key-setting should be visible and the buttons should be disabled: https://xd.adobe.com/view/2690f082-d88d-4788-5db7-b04c9474a404-50a1/screen/895ab0f6-bb8f-49b9-a46b-2f36a42be8a2/-HDX-Data-Source-NOT-configured

### TODO:
- Check if API-key for HDX is set
- If not, display screen b
- If it is, display screen a
- Add a blank directive for hdx-tagging
- Add a test-file for the hdx-directive
- When clicking on the HDX-button, the hdx-directive should be displayed

### QA-test checklist
Assuming HDX-flag is on
- Go to settings-data-export without any api-key saved (<-- this cannot be tested since the qa-user already has an api-key saved)
- [ ] 3 buttons should be visible, the last one greyed out
- [ ] An alert with a link to api-key-config should be visible
- Configure api-key and go back to settings-data-export 
- [ ] 3 buttons should be visible, all of them active (<-- start testing here)
- [ ] Click on the button that says "Assign tags and attributes"
- [ ] You should be directed to the tags and attributes page (doesnt need to contain anything at this stage, but the final result should look like this: https://xd.adobe.com/view/2690f082-d88d-4788-5db7-b04c9474a404-50a1/screen/9a17d59a-cdfd-4ed4-aec5-573cdfeadb97/Data-export-HDX-single-survey)

**Comment by Angamanga** [comment]
@Eve-wanderi Could you check the QA-checklist to see if something is missing?

**Comment by Angamanga** [comment]
@rowasc Could you please review?

**Comment by Angamanga** [comment]
@Erioldoesdesign I just realised something, the text here:
![Screen Shot 2018-05-08 at 16.10.52.png](https://images.zenhubusercontent.com/5a6f2bce4b5806bc2bc4b158/3fca4424-ae34-4dc3-b1db-ab4a110f5df4) 

What if they just want to export tagged data to csv?

**Comment by Erioldoesdesign** [comment]
@Angamanga They would still be able to do that (export CSV) that's why we 'strongly advise' that they do it but it's not compulsory.

This may not be an ideal flow for show. Definitely worth testing post v0 and validating/amending :)

**Comment by Angamanga** [comment]
@Erioldoesdesign Ah, ok, so the button should not be disabled?

**Comment by Erioldoesdesign** [comment]
ah sorry @Angamanga I got confused as to what screen we were on here. So this is this screen: 
<img width="781" alt="screen shot 2018-05-10 at 17 11 11" src="https://user-images.githubusercontent.com/11681324/39877058-2e7dee5c-5475-11e8-9425-ad21bee4f5f0.png">

And yes, the tagging/attributes button is greyed out! so yes they need to config the API first before they can even do a CSV. Apologies! crossed wires

**Comment by Angamanga** [comment]
@Eve-wanderi Ready for QA :)
