### ISSUE TITLE
[Platform Client] Add attributes and tags to a field

### ISSUE THREAD

**Issue by Angamanga** [ushahidi/platform-client#1120]
### Description
- Every survey-field can have one tag and many attributes.
- User can add as many attributes as they want to each field
- The final HDX=tag should be visible in an icon and look like the designs https://xd.adobe.com/view/2690f082-d88d-4788-5db7-b04c9474a404-50a1/screen/63bd5779-ab74-4c2f-8dcd-61eff5839a54/Data-export-HDX-single-survey-19
- When an attribute is selected, it becomes greyed out in the dropdown and appears in the icon to the right
- When an attribute is removed from the icon, this attribute is not greyed out in the dropdown anymore
- When the icon is closed, all tags and attributes are available in the dropdowns and not greyed out
- A survey-field can be left without a tag

## TODO
- Add the logic to assign tags and attributes to a field 
- Add the UI-component to display the final tag for each field
- Add a variable to store the selected tags and fields to be sent to the api for exporting csv/sending to hdx <- @rowasc How does the api want the tags/field/survey-ids? 

## QA-checklist
Assumes HDX-feature-flag is on and api-key is added for hdx
- Go to settings-data-export-add tags and attributes
- [ ] There should be a table visible with the available surveys, survey-fields as rows and tags and attributes for each fields as dropdowns
- select one field
- [ ] the first dropdown (for tags) in that row should become active
- Select a tag
- [ ] the tag should appear as an icon in the end of the row according to designs (<-- known error, its just a list in plain text right now)
- Select an attribute
- [ ] the attribute should be attached to the icon according to designs (<-- known error, its just a list in plain text right now)
- Select another field
- Select a tag and an attribute
- Click on the "Add another hdx attribute link"
- [ ] Another dropdown should be visible with all attributes available, the previously selected ones for that field should be greyed out.
- deselect the last attribute
- [ ] this attribute should disappear from the icon <-- this is just a list in plain text, not an icon, known error 
- add another attribute
- [ ] this new attribute should appear in the icon <-- this is just a list in plain text not an icon, known error
- select another attribute in the same dropdown
- [ ] the newly selected attribute should appear in the icon instead of the old one

**Comment by Erioldoesdesign** [comment]
1 - All previously added attributes should be grey'd out but occupy the same spot in the list they did previously (this is mostly so a user can re-read the description in the dropdown of an attribute) 

It also helps unfamiliar users of hxl to learn by processing the steps in the UI and gives them a third confirmation (1st confirmation is the drop down display, 2nd is the tag preview)

**Comment by Angamanga** [comment]
@Eve-wanderi Could you double-check the QA-list, is there anything missing you would like to add?

**Comment by Angamanga** [comment]
@rowasc Could you please review?

**Comment by rowasc** [comment]
@Angamanga looks good. Regarding:  "How does the api want the tags/field/survey-ids?" , this is the endpoint description for that. https://github.com/ushahidi/platform/issues/2805

**Comment by Angamanga** [comment]
@Eve-wanderi Ready for QA :)

**Comment by Eve-wanderi** [comment]
1. I see a diffrence with what is in the design and what is currently there. Highlighted the areas where we have the diffrence.

![attributes.png](https://images.zenhubusercontent.com/5a730b1e4b5806bc2bc534d6/9bbad80f-3c4d-471c-b716-01d6b8ecc431)

2.  Noticed that if user adds a wrong "Maintainer" System does not give the user a validation message that the Maintainer is wrong. Instead user has to wait untill attributes are uploaded then check on export history. Best way would be to let users know that the maintainer field is wrong before they can proceed to export.

3. No validation message incase HDX Upload or Export Fails. i.e System does not inform users of failed exports instead it just shows Dismiss. Users cannot understand what this means. (See below)

![image.png](https://images.zenhubusercontent.com/5a730b1e4b5806bc2bc534d6/c0861430-ef0b-4a6b-9c4e-afec581ffaac)

**Comment by Erioldoesdesign** [comment]
@Eve-wanderi Awesome work Eve, I know in regards to point 1. Anna & Seth on the front-end made me aware of these front-end differences to the designs and we're okay with this as it doesn't massively impact the usability for version 0.

Anna is off this afternoon but I don't think number 1 should halt 'completing' the development work and could be rolled into next cycle for improvements but it's for sure @jrtricafort 's call :)

**Comment by jrtricafort** [comment]
@Erioldoesdesign Agree that Point #1 shouldn't be blocking.

@Eve-wanderi Thank you for identifying points #2 and #3. I will make a new ticket for the next HDX Epic, which will include these notification changes.

**Comment by jrtricafort** [comment]
@Eve-wanderi has tested this, and I have also tested this. @willdoran  I think we can move this into Closed, correct?

**Comment by jrtricafort** [comment]
Added https://github.com/ushahidi/platform/issues/2988 to capture notification bar improvements for v1.
